---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

#Part 1: Data Collection + Format
```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(zoo)


library(shiny)
library(sf)
library(leaflet)
library(ggplot2)
library(DT)

poverty <- read_csv("Data/poverty/ACSST5Y2020.S1701-Data.csv")
age_race <- read_csv("Data/age_race/ACSDP5Y2020.DP05-Data.csv")
education <- read_csv("Data/education/ACSST5Y2020.S1501-Data.csv")
language <- read_csv("Data/language_spoken/ACSST5Y2020.S1601-Data.csv")
living_alone <- read_csv("Data/living_alone/ACSST5Y2020.S1101_2024-04-09T014526/ACSST5Y2020.S1101-Data.csv")
```


```{r}
# remove first row, calcuate percentage, keep only relevant variables: 
language <- language[-1, ]
# language <- language%>%
#   mutate(eng_less_than_well = 100*(as.integer(S1601_C05_001E) / as.integer(S1601_C01_001E)))%>%
#   select(GEO_ID, eng_less_than_well)
language <- language %>%
  mutate(eng_less_than_well = 100 * (as.integer(S1601_C05_001E) / as.integer(S1601_C01_001E))) %>%
  dplyr::select(GEO_ID, eng_less_than_well)  # Using dplyr::select explicitly

education <- education[-1, ]
education <- education %>%
  mutate(adults_not_high_school_grads = 100*(1 - (as.integer(S1501_C01_014E) / as.integer(S1501_C01_006E))))%>%
  select(GEO_ID, adults_not_high_school_grads)

poverty <- poverty[-1, ]
poverty <- poverty%>%
  mutate(in_poverty = 100*(as.integer(S1701_C02_001E) / as.integer(S1701_C01_001E)))%>%
  select(GEO_ID, in_poverty)


age_race <- age_race[-1, ]
# age_race <- age_race%>%
#   select(GEO_ID, NAME, DP05_0001E, DP05_0005E, DP05_0015E, DP05_0016E, DP05_0017E, DP05_0037PE)

age_race <- age_race%>%
  mutate(age_0_4 = 100* (as.integer(DP05_0005E) / as.integer(DP05_0001E)))%>%
  mutate(age_65_older = 100*(as.integer(DP05_0015E) + as.integer(DP05_0016E) + as.integer(DP05_0017E))
         / as.integer(DP05_0001E))%>%
  mutate(non_white =  100*((100 - as.integer(DP05_0037PE)) / 100))%>%
  select(GEO_ID, age_0_4, age_65_older, non_white)

living_alone <- living_alone[-1, ]
living_alone <- living_alone %>%
  mutate(living_alone_65_older = 100*(as.integer(S1101_C01_013E) / as.integer(S1101_C01_001E)))%>%
  select(GEO_ID, living_alone_65_older)

# living_alone%>%
#   select(GEO_ID, NAME,S1101_C01_001E, S1101_C01_012E, S1101_C01_013E)

```

```{r}
df2 <-left_join(age_race, poverty, by = c("GEO_ID"))
df3 <- left_join(df2, language, by = c("GEO_ID"))
df4 <- left_join(df3, education, by = c("GEO_ID"))
df5 <- left_join(df4, living_alone, by = c("GEO_ID"))
```


## health factors
```{r}
diabetes <- read_csv("Data/Health/diabetes.csv")
diabetes <- diabetes%>% 
  filter(`Period of Measure` == 2021)%>%
  rename( diabetes = `Indicator Rate Value`)%>%
  select(Location, diabetes)

obesity <- read_csv("Data/Health/obesity.csv")
obesity <- obesity %>%
  filter(`Period of Measure` == 2021)%>%
  rename( obesity = `Indicator Rate Value`)%>%
  select(Location, obesity)

cognitive <- read_csv("Data/Health/cognitive_issue.csv")
cognitive <- cognitive%>%
  filter(`Period of Measure` == "2018-2022")%>%
  rename( cognitive_problem = `Indicator Rate Value`)%>%
  select(Location, cognitive_problem)
```

```{r}
hdf1 <- left_join(obesity, diabetes, by = join_by(Location))
hdf2 <- left_join(cognitive, hdf1)
```
```{r}
tracts_zips <- read_csv("Data/TractsWithZipCode.csv")%>%
  select(GEOID, ZipCode)%>%
  rename(`Zip Code` = ZipCode)

hospitals <- read_excel("Data/Heat_Dane_2016_2022.xlsx")%>%
  select(`Zip Code`, Total)

hospitals$`Zip Code` = as.numeric(hospitals$`Zip Code`)

hosp <- left_join(tracts_zips, hospitals)%>%
  select(GEOID, Total)%>%
  rename(num_hospitalizations= Total)%>%
  rename(Location = GEOID)
hdf3 <- left_join(hdf2, hosp)
# hosp%>%
#   filter(`Zip Code` == 53704)
```

```{r}
surf <- read_csv("Data/temp/Impervious Surface and Temperature Data/DaneTractsImperviousness.csv")
surf <- surf%>%
  select(GEOID, Imperv_Pct)

temp <- read_csv("Data/temp/Impervious Surface and Temperature Data/DaneTractsTemp082423.csv")
temp <- temp%>%
  select(GEOID, maxtemp_c)

tdf <- left_join(temp, surf)
```

```{r}
# joining health, demographic, and environment data
df5$GEO_ID <- substr(df5$GEO_ID, 10, 20)

df5 <- df5%>%
  rename(GEOID = GEO_ID)
  
df5$GEOID <- as.numeric(df5$GEOID)

hdf3 <- hdf3%>%
  rename(GEOID = Location)

combined_df <- left_join(df5, hdf3)
combined_df2 <- left_join(combined_df, tdf)
```

now statistical analysis: 

```{r}
# replace missing data with mean for that coulumn
df_full <- na.aggregate(combined_df2, FUN = mean)
```

# Part 2: Perform PCA on df_full

```{r}
library(psych)
# take out GEOID before PCA
pca_prepped <- df_full%>%
  select(-GEOID)

# Perform PCA with varimax rotation
pca_rotated <- principal(pca_prepped, rotate="varimax", nfactors=4, scores=T)

# pca_rotated$scores[,1:5]  # Scores returned by principal()
df_pca <- as_tibble(pca_rotated$scores)
# sum principal components, normalize
norm_df <- df_pca%>%
  mutate(
         total_p = RC2+RC4+RC3+RC1,
         vulnerability_score = 100 * (percent_rank(total_p))
         )

# rejoin GEOID to scores
metadata <- df_full %>%
  select(GEOID)
hvi <- cbind(metadata, norm_df)%>%
  select(GEOID, vulnerability_score)

df_pca_rejoined <- cbind(metadata, df_pca)
```

```{r}
scores <- pca_rotated$values
# pca_rotated$Structure
# 
# data <- data.frame(index = 1:length(scores), score = scores)
# 
# 
# plot <- ggplot(data, aes(x = index, y = score)) +
#   geom_point() +  # Add points
#   labs(x = "Component", y = "Eigenvalue") +  # Label axes
#   ggtitle("Scree Plot")  # Add a title
# plot
#plot(pca_rotated$values)
#ggsave("scree_plot.png", plot, width = 6, height = 4, dpi = 300)
```


```{r}
# library(ceramic)
# library(raster)
# library(terra)
# library(tidyverse)
# library(tmap)
# theme_set(theme_minimal())
```

```{r}
dane_county <- read_sf("CensusTractData-selected/DaneCensusTracts.shp")
dane_county$GEOID <- as.numeric(dane_county$GEOID)
hw4_df <- left_join(dane_county, hvi, by = "GEOID")
hw4_df2 <- left_join(hw4_df, df_full, by = "GEOID")
hw4_df3 <- left_join(hw4_df2, df_pca_rejoined, by = "GEOID")

# tm_shape(hw4_df3)+
#    tm_polygons(col= "vulnerability_score")


dt_df <- left_join(hvi, df_full, by = "GEOID")
dt_df2 <- left_join(df_pca_rejoined, dt_df, by = "GEOID")
```

```{r}
# th <- theme_minimal() + 
#   theme(
#     panel.grid.minor = element_blank(),
#     panel.background = element_rect(fill = "#f7f7f7"),
#     panel.border = element_rect(fill = NA, color = "#0c0c0c"),
#     axis.text = element_text(size = 14),
#     axis.title = element_text(size = 16),
#     strip.text = element_text(size = 16),
#     legend.position = "bottom"
#   )
# theme_set(th)
# 
df <- as.data.frame(pca_rotated$weights)
# df
# 
df_long <- df %>%
  rownames_to_column(var = "Variable") %>%
  pivot_longer(-Variable, names_to = "Component", values_to = "Value")
# 
# # Plot using ggplot
# ggplot(df_long, aes(x = Value, y = Variable)) +
#   geom_col(position = "dodge", width = 0.6) +
#   facet_grid(~ Component)+
#   labs(x = "Variable", y = "Value", title = "Principal Components Visualization")
```


```{r}
# library(shiny)
# library(sf)
# library(leaflet)
# library(ggplot2)
# library(DT)

# Define color palette
pal <- colorNumeric(
  palette = c("#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"),
  domain = hw4_df3$vulnerability_score
)

ui <- fluidPage(
  titlePanel("Dane County Heat Vulnerability Index"),
  fluidRow(
    column(
      width = 12,
      uiOutput("info_text"))),

  fluidRow(
    column(
      width = 6,
      leafletOutput("map", width = "100%", height = 600)
    ),
    column(
      width = 6,
      plotOutput("ggplot", width = "100%", height = 600)
    )
  ),
  fluidRow(
    column(
      width = 12,
      DT::dataTableOutput("data_table")
    )
  )
)

# Define server logic
server <- function(input, output) {
  output$info_text <- renderUI({
  HTML("Extreme heat is known to have negative impacts on human health in terms of morbidity and mortality. As temperatures continue to increase as a result of climate change, we can expect to see more extreme heat events. Many of the established risk factors for heat-related mortality disproportionately affect elderly populations, socially isolated individuals, and those with preexisting chronic conditions. This visualization attempts to display potential areas of highest risk to extreme heat in Dane County, with the ultimate goal of allowing for targeted public health interventions")
})

  # Render map
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("CartoDB.Positron") %>%
      addPolygons(data = hw4_df3, fillColor = ~pal(hw4_df3$vulnerability_score), fillOpacity = 0.7,
                  color = "white", stroke = TRUE, weight = 1,
                  popup = paste("Census Tract: ", hw4_df3$GEOID, "<br>",
                                "Vulnerability Score: ", hw4_df3$vulnerability_score, "<br>",
                                "PC1 Score: ", hw4_df3$RC1, "<br>",
                                "PC2 Score: ", hw4_df3$RC2, "<br>",
                                "PC3 Score: ", hw4_df3$RC3, "<br>",
                                "PC4 Score: ", hw4_df3$RC4
                                ))
  })

  # Render ggplot graph
  output$ggplot <- renderPlot({
    ggplot(df_long, aes(x = Value, y = Variable)) +
      geom_col(position = "dodge", width = 0.6) +
      facet_grid(~ Component)+
      labs(x = "Variable", y = "Value", title = "Principal Components Visualization")
  })
  # Render data table
output$data_table <- DT::renderDataTable({
  datatable(hw4_df3)})
}
# Run the application
shinyApp(ui = ui, server = server)
```

